[tools]
"aqua:ariga/atlas" = "0.38.0"
"aqua:golangci/golangci-lint" = "2.9.0"
go = "1.25"
node = "22"
"npm:@biomejs/biome" = "latest"
"npm:@openai/codex" = "latest"
"npm:prettier" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
python = "3.12"
flutter = "3.38.3"
"npm:agent-browser" = "latest"
ruby = "4"
bun = "latest"
prek = "latest"

[settings]
experimental = true
